[tool.poetry]
name = "ytm"
version = "0.1.0"
description = ""
authors = ["Shubh Chudasama <shubh.cs@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
xdg = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
